# Default values for jbok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jbok
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

nodeSelector: {}

chain:
  nodes: 1
  nodeInfos: 
    node_0:
      nodekey: 691c02e71a087069d34ad8fcb15bb89456ee097274837b1075935b977bd1f33f
      miner: fe262870ba837633276aab97d86f91a057f8e902
      keystore: |-
        {
          "id" : "daf99906-ce1a-4086-9044-d6c92fdc4140",
          "address" : "fe262870ba837633276aab97d86f91a057f8e902",
          "crypto" : {
            "cipher" : "aes-128-ctr",
            "ciphertext" : "d1889b7281d211181c04ca5a61b79bc1ffc5f2a64c09fc0970bfdb66a243c629",
            "cipherparams" : {
              "iv" : "e203a4bd39dc3fb3b545ac2950552ab4"
            },
            "kdf" : "scrypt",
            "kdfparams" : {
              "salt" : "06c1d7a6c40e8878db251e313d12c3d6fa317d0c63f172a288ced39b7f699cdc",
              "n" : 262144,
              "r" : 8,
              "p" : 1,
              "dklen" : 32
            },
            "mac" : "af7612fb8c86fd1c6b58419687ded6b92cc9a143309fc043b9b50602297e081b"
          },
          "version" : 3
        }
jbok:
  identity: test

rpc:
  service: 
    port: 20002
    type: NodePort
    loadBalance: true

peer:
  service:
    type: ClusterIP
    port: 20000

persistence:
  enabled: false
  size: 1Gi
  storageClass: hostpath
  accessMode: ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"