# Default values for jbok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jbok
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

nodeSelector: {}

chain:
  nodes: 1

jbok:
  identity: test
  node:
    service:
      type: LoadBalancer
  simulation:
    replicaCount: 1
    service:
      type: LoadBalancer

persistence:
  enabled: true
  size: 1Gi
  storageClass: hostpath
  accessMode: ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"