{{ range (until (.Values.chain.nodes | int)) }}
{{- $nodeNumber := printf "%03d" . }}
{{- $nodeIndex := . }}
---
apiVersion: v1
data:
  app.json: |-
    {
      "identity" : "{{ $.Values.jbok.identity }}-{{ $nodeNumber }}",
      "logLevel" : "DEBUG",
      "logHandler" : "console,file",
      "genesisConfig" : null,
      "history" : {
        "dbBackend" : "leveldb",
        "frontierBlockNumber" : "0",
        "homesteadBlockNumber" : "0",
        "tangerineWhistleBlockNumber" : "0",
        "spuriousDragonBlockNumber" : "0",
        "byzantiumBlockNumber" : "0",
        "constantinopleBlockNumber" : "1000000000000000000000",
        "difficultyBombPauseBlockNumber" : "3000000",
        "difficultyBombContinueBlockNumber" : "5000000"
      },
      "keystore" : {
        "dbBackend" : "file"
      },
      "peer" : {
        "port" : 20000,
        "host" : "localhost",
        "nodekey" : null,
        "enableDiscovery" : false,
        "discoveryPort" : 20001,
        "dbBackend" : "leveldb",
        "bootUris" : [
        ],
        "updatePeersInterval" : "10seconds",
        "maxOutgoingPeers" : 10,
        "maxIncomingPeers" : 10,
        "maxPendingPeers" : 10,
        "timeout" : "10seconds"
      },
      "sync" : {
        "maxConcurrentRequests" : 50,
        "maxBlockHeadersPerRequest" : 128,
        "maxBlockBodiesPerRequest" : 128,
        "maxReceiptsPerRequest" : 60,
        "maxNodesPerRequest" : 200,
        "minPeersToChooseTargetBlock" : 2,
        "minBroadcastPeers" : 4,
        "fullSyncOffset" : 10,
        "fastSyncOffset" : 64,
        "fastEnabled" : false,
        "retryInterval" : "15seconds",
        "checkForNewBlockInterval" : "5seconds",
        "banDuration" : "200seconds",
        "requestTimeout" : "10seconds"
      },
      "txPool" : {
        "poolSize" : 4096,
        "transactionTimeout" : "10minutes"
      },
      "mining" : {
        "enabled" : true,
        "ommersPoolSize" : 30,
        "blockCacheSize" : 30,
        "minerKeyPair" : null,
        "minerAddress" : {{ (index $.Values.chain.nodeInfos ( printf "node_%d" $nodeIndex )).miner | quote }},
        "coinbase" : "0000000000000000000000000000000000000042",
        "extraData" : "",
        "mineRounds" : 100000,
        "period" : "5seconds",
        "epoch" : "30000",
        "checkpointInterval" : 1024
      },
      "rpc" : {
        "enabled" : true,
        "host" : "0.0.0.0",
        "port" : 20002,
        "apis" : "public,admin,personal"
      },
      "consensusAlgo" : "clique"
    }
  genesis.json: |-
    {
      "nonce" : "42",
      "difficulty" : "1024",
      "extraData" : "dbd594fe262870ba837633276aab97d86f91a057f8e902c380808000",
      "gasLimit" : "16716680",
      "coinbase" : "0000000000000000000000000000000000000000",
      "alloc" : {
        "0xfe262870ba837633276aab97d86f91a057f8e902" : "10000000000000000000000000000",
        "0xfe84089b461ec2e5e65578ae56891d7fe990ebac" : "10000000000000000000000000000",
        "0x41bdeeb5a14f024070b73c4fed6f45f2f62b8499" : "10000000000000000000000000000",
        "0x2be1cab7edf45970a3d1b4e2106a6ec26af2f08c" : "10000000000000000000000000000"
      },
      "chainId" : "1",
      "timestamp" : 1548323258777
    }
  nodekey: {{ (index $.Values.chain.nodeInfos ( printf "node_%d" $nodeIndex )).nodekey | quote }}
kind: ConfigMap
metadata:
  name: {{ template "jbok.name" $ }}-config-{{ $nodeNumber }}
  namespace: default
  labels:
    app: {{ template "jbok.name" $ }}
    chart: {{ template "jbok.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    nodeNumber: {{ $nodeNumber | quote }}
{{- end }}