apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "jbok.name" . }}
    chart: {{ template "jbok.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name:  {{ template "jbok.fullname" . }}-rpc
spec:
  type: {{ .Values.rpc.service.type }}
{{- if .Values.rpc.service.loadBalance }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
{{- end }}
  ports:
    - name: rpc
      port: {{ .Values.rpc.service.port }}
      targetPort: {{ .Values.rpc.service.port }}
      nodePort: 30002
  selector:
    app: {{ template "jbok.name" . }}
    release: {{ .Release.Name }}
{{- if not .Values.rpc.service.loadBalance }}
    nodeNumber: {{ .Values.rpc.service.node | quote }}
{{- end }}