{{ range (until (.Values.chain.nodes | int)) }}
{{- $nodeNumber := printf "%03d" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jbok.fullname" $ }}-{{ $nodeNumber }}
  labels:
    app: {{ template "jbok.name" $ }}
    chart: {{ template "jbok.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ $.Values.peer.service.type }}
  ports:
    - name: peer
      port: {{ $.Values.peer.service.port }}
      targetPort: peer
      protocol: TCP
  selector:
    app: {{ template "jbok.name" $ }}
    release: {{ $.Release.Name }}
    nodeNumber: {{ $nodeNumber | quote }}
{{- end }}