apiVersion: v1
kind: Service
metadata:
  name: {{ template "jbok.fullname" . }}-node
  labels:
    app: {{ template "jbok.name" . }}
    chart: {{ template "jbok.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 20002
      name: rpc
  selector:
    app: {{ template "jbok.name" . }}
    release: {{ .Release.Name }}
